### ISSUE TITLE
Is there a need for db/access.php

### ISSUE THREAD

**Issue by mudrd8mz** [AnsonArgyris/moodle-atto_oembed#15]
I am wondering about your reasoning and use cases for the `db/access.php`. As a consequence of having it like now, your plugin is only available to users who are enrolled in a course (so it is not displayed when the user is editing own profile or composes a blog post).

Do you really need to check for permissions? Is there a valid use case that the plugin should be available for certain roles only? Would not it be better to simply remove the file and the relevant permission checks?

**Comment by AnsonArgyris** [comment]
Hello!

I did not really think about it, to be honest.
I used moodle-atto_newtemplate made by Justin Hunt as base for my
plugin. And i thought it would be wise to leave the access control in
there. So i dont really have a usecase and i will just remove the file.

Best wishes!

**Comment by AnsonArgyris** [comment]
done
