### ISSUE TITLE
Requires enabletrusttext

### ISSUE THREAD

**Issue by mudrd8mz** [AnsonArgyris/moodle-atto_oembed#17]
This has been originally open in my comment at https://moodle.org/plugins/view/atto_oembed however I think this will be better place to discuss it.

> Thanks Erich for sharing the plugin with the community. I must admit I
> am not quite sure about the actual benefits of it though. Thing is, to
> use the oEmbed protocol this way, you end up with the provider's HTML
> code fragment injected into the text body. Many of the supported
> providers use `<iframe>` to display their contents. As far as I know, to
> be able to save and use HTML text with `<iframe>`, the trusted content
> feature `$CFG->enabletrusttext` must be enabled and properly set up at the
> server. Admins should be well aware of all the consequences of such
> setup before attempting to allow it. That is also why implementing
> oEmbed as a filter is imho better (and safer) solution.
> 
> Maybe you could re-think the overall design and purpose of this Atto
> plugin and turn it into a user-friendly frontend for the oEmbed filter
> functionality?
> 
> I would like to discuss these concerns more prior approving this plugin
> here. Thanks for your understanding and the patience with the approval
> process.

**Comment by AnsonArgyris** [comment]
Thank you for taking the time to review our plugin.

The main benefits of the Atto o-embed plugin are

a) You see the result of the o-embed immediately
b) You see the o-embed element in context
c) It’s a modern and expected pattern of behaviour to add an o-embed link and see the result immediately - see how Tumbler, Twitter and Facebook do it for example.
d) You can selectively have some links as simply links and others as o-embed - you can’t do this with the existing o-embed filter which indiscriminately converts all links.

How we suggest we approach the issue of o-embed iframes:

1) We put a wrapper around the o-embed code with a class of ‘atto-oembed’
2) We write our own filter to accompany the atto plugin which targets the wrappers and adds in the missing iframe o-embed code.

Is there a chance of the plugin getting accepted if we do this changes?

**Comment by mudrd8mz** [comment]
Well, sure. The filter is indeed a cleaner solution. Is not there a way to re-use the existing filter though? Are there some technical reasons why you need an own one?
